# Generated by Django 4.2.18 on 2025-03-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='description',
            new_name='student_name',
        ),
    ]
