# Generated by Django 4.2.18 on 2025-03-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_description_seminar_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cps_email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='cps_phone',
            new_name='student_phone',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='student_name',
        ),
        migrations.CreateModel(
            name='Seminar_studet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(unique=True)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seminar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
