# Generated by Django 4.2.18 on 2025-03-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_description_payment_model_seminar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar_studet',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='seminar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
