# Generated by Django 4.2.18 on 2025-03-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_seminar_studet_payment_id_seminar_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='name',
        ),
    ]
