# Generated by Django 4.2.18 on 2025-03-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_student_name_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
    ]
