# Generated by Django 4.2.18 on 2025-03-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
