# Generated by Django 4.2.18 on 2025-03-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_seminar_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
