# Generated by Django 4.2.18 on 2025-03-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_seminar_name_remove_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminar_name', models.CharField(max_length=500, verbose_name='Название семинара')),
                ('student_name', models.CharField(max_length=255, verbose_name='ФИО студента')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Email студента')),
                ('student_phone', models.CharField(max_length=20, verbose_name='Телефон студента')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Регистрация на семинар',
                'verbose_name_plural': 'Регистрации на семинары',
                'ordering': ['-registration_date'],
            },
        ),
    ]
