# Generated by Django 4.2.18 on 2025-03-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_seminarregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarregistration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='seminar_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название семинара'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email студента'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО студента'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='student_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон студента'),
        ),
    ]
